name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v6
      - name: Setup Node.js 🟢
        uses: actions/setup-node@v6
        with:
          node-version: 24 # Usaremos a 24 que é a LTS (estável) para evitar conflitos
          cache: 'npm'

      - name: Cypress run 🏁
        uses: cypress-io/github-action@v7
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          record: true
          
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
