name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4 # Atualizei para v4 que é a mais estável

      - name: Setup Node.js 🟢
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Usaremos a 20 que é a LTS (estável) para evitar conflitos
          cache: 'npm'

      - name: Install dependencies 📦
        run: npm install

      - name: Cypress run 🏁
        uses: cypress-io/github-action@v6 # v6 ou v7 funcionam bem aqui
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          #record: true
          
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
